---
- name: "check if this is really ubuntu"
  fail:
    msg: "This role is only supported for Ubuntu hosts"
  when: ansible_distribution != 'Ubuntu'


- name: add docker GPG apt key
  become: yes
  become_method: sudo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu groovy stable
    state: present

- name: udate apt and install docker-ce
  become: yes
  become_method: sudo
  apt: 
    update_cache: yes
    name: docker-ce 
    state: latest

- name: ensure group "docker" exists
  become: yes
  become_method: sudo
  group:
    name: docker
    state: present

- name: adding user vagrant to group docker
  become: yes
  become_method: sudo
  user:
    name: vagrant
    groups: docker
    append: yes
